version: '3'

services:
  app:
    container_name: golang_microservice
    image: golang:latest
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./:/go/src
    restart: 'always'
  rabbitmq:
    container_name: rabbitmq_golang_microservices
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
